# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsHub
  pod 'SwiftSoup'
  pod 'FeedKit', '~> 9.0'

  target 'NewsHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsHubUITests' do
    # Pods for testing
  end

end
